name: Build Rules

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * *"
      timezone: "Asia/Shanghai"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: 删除历史运行记录
        if: always()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run list \
            --workflow "${{ github.workflow }}" \
            --status completed \
            --limit 1000 \
            --json databaseId \
            --jq '.[].databaseId' |
          while read -r run_id; do
            echo "删除历史运行: $run_id"
            gh api \
              --method DELETE \
              "repos/${{ github.repository }}/actions/runs/$run_id"
          done

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache-dependency-path: ./custom/go.sum

      - name: Checkout Loyalsoldier/geoip
        uses: actions/checkout@v4
        with:
          repository: Loyalsoldier/geoip
          path: geoip

      - name: Checkout MetaCubeX/meta-rules-converter
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/meta-rules-converter
          path: convert

      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: community

      - name: Build
        run: bash build.sh

      - name: Publish dist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan dist
          git rm -rf . || true
          git --work-tree=dist add -A .
          git commit -q -m "update $(TZ='Asia/Shanghai' date '+%F %T')"
          git push origin dist --force
