name: Build Rules

permissions:
  contents: write

on:
  schedule:
    - cron: "0 23 * * *" # 7:00 AM UTC+8
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache-dependency-path: ./custom/go.sum

      - name: Loyalsoldier/geoip
        run: |
          go install -v github.com/Loyalsoldier/geoip@latest

      - name: Checkout MetaCubeX/meta-rules-converter
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/meta-rules-converter
          path: convert

      - name: Build
        run: bash build.sh

      - name: Publish dist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan dist
          git rm -rf . || true
          git --work-tree=dist add -A .
          git commit -q -m "update $(TZ='Asia/Shanghai' date '+%F %T')"
          git push origin dist --force
